server:
  port: 9023
spring:
  application:
    name: mss-resource
  zipkin:
      base-url: ${monitor.url}
endpoints:
  health:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false
security:
  oauth2:
    resource:
      id: mss-resource
      user-info-uri: ${gateway.auth.info.url.out}
      prefer-token-info: false