server:
  port: 9060

spring:
  application:
    name: mss-oauth
  jpa:
    show-sql: true
  datasource:
    url: ${mysql.url}
    username: ${mysql.username}
    password: ${mysql.password}
    druid:
      driver-class-name: ${mysql.driver}
  redis:
    host: ${redis.ip}
    port: ${redis.port}
    password: ${redis.pwd}
logging:
  config: classpath:logback.xml
  level:
    org:
      springframework:
        web: info
###feign 默认关闭熔断，请看HystrixFeignConfiguration
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1