spring:
  application:
    name: mss-gateway
server:
  port: 9030
#eureka:
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#    lease-renewal-interval-in-seconds: 5
#    lease-expiration-duration-in-seconds: 10
#  client:
#      service-url:
#        defaultZone: http://mss-eureka1:9010/eureka/,http://mss-eureka2:9011/eureka/
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    uaa:
      path: ${route.path}
      strip-prefix: true
      sensitiveHeaders:
      serviceId: mss-oauth
security:
  oauth2:
    client:
       ##网关的地址
      access-token-uri: ${gateway.token.url}
      user-authorization-uri: ${gateway.auth.url}
      client-id: ${gateway.client.id}
      client-secret: ${gateway.client.secret}
    resource:
      user-info-uri: ${gateway.auth.info.url}
      prefer-token-info: false
##############end#####################
####超时配置####
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 600000
###超时配置###